server:
  port: 7008
spring:
  application:
    name: admin-ext
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
dubbo:
  application:
    name: admin-ext
  protocol:
    port: 20901
  registry:
    address: zookeeper://192.168.140.129:2181
